export default function AboutPage() {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative pt-20 pb-20 bg-gradient-to-br from-pink-400 via-purple-400 to-orange-300 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-pink-400/90 via-purple-400/90 to-orange-300/90"></div>
        
        <div className="container mx-auto px-8 relative z-10">
          <div className="max-w-4xl mx-auto pt-24 text-center">
            <div className="inline-flex items-center px-4 py-2 rounded-full bg-white/20 backdrop-blur-sm border border-white/30 mb-8">
              <div className="w-2 h-2 bg-white rounded-full mr-3"></div>
              <span className="text-sm text-white font-medium">About Us</span>
            </div>
            
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-light leading-tight text-white drop-shadow-lg mb-8">
              Meet Abode
            </h1>
            
            <p className="text-xl md:text-2xl text-white/90 font-light max-w-3xl mx-auto leading-relaxed drop-shadow">
              The world's first AI-generated property management system
            </p>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="py-24 bg-white">
        <div className="container mx-auto px-8">
          <div className="max-w-4xl mx-auto space-y-16">
            
            {/* Introduction */}
            <div className="space-y-8">
              <div className="w-16 h-1 bg-gradient-to-r from-purple-400 to-orange-400 rounded-full"></div>
              
              <div className="space-y-6 text-lg leading-relaxed font-light text-gray-700">
                <p>
                  Built from the ground up by artificial intelligence, Abode replaces outdated, manual tools with intelligent automation that actually thinks. Every workflow is powered by AI Modules that act like digital team members, handling inspections, maintenance, leasing, compliance, finance and communication with speed and precision.
                </p>
                
                <p>
                  Abode adapts to your agency's preferences, follows Australian legislation, and evolves in real time. It learns your processes, automates the grunt work and keeps you in full control.
                </p>
                
                <p className="text-xl font-medium text-gray-900">
                  No spreadsheets. No double handling. No waiting for updates.
                </p>
                
                <p>
                  This is not just smarter software. It's a new standard for property management. Abode is fast, flexible and built for the future. Ready when you are.
                </p>
              </div>
            </div>

            {/* AI-Generated Foundation */}
            <div className="space-y-8">
              <h2 className="text-3xl md:text-4xl font-light text-gray-900 leading-tight">
                Built from the ground up with AI
              </h2>
              
              <div className="space-y-6 text-lg leading-relaxed font-light text-gray-700">
                <p>
                  We're not just adding artificial intelligence to property software. We're rebuilding the entire experience using AI as the foundation. Abode is a bold rethink of how property management should work when built from the ground up for speed, intelligence and automation.
                </p>
                
                <p>
                  Every feature, every workflow, every screen in Abode is generated by AI, not by hand. The result is a system that's not only smarter, but faster to adapt, easier to use and capable of handling real-world complexity without compromise.
                </p>
                
                <p>
                  The property industry has been left behind by tech for too long. Managers are overwhelmed. Landlords are frustrated. Tenants are disengaged. Abode exists to change that, not by streamlining the old way of doing things, but by building a new one entirely.
                </p>
              </div>
            </div>

            {/* AI Modules */}
            <div className="space-y-8">
              <h2 className="text-3xl md:text-4xl font-light text-gray-900 leading-tight">
                Property management, reimagined
              </h2>
              
              <div className="space-y-6 text-lg leading-relaxed font-light text-gray-700">
                <p>
                  At the heart of Abode are AI Modules, intelligent, task-specific agents that act like digital team members inside your agency. These Modules can handle everything from inspections and maintenance to lease renewals, trust accounting and compliance, all in real time, with no need for manual follow-up.
                </p>
                
                <p className="text-xl font-medium text-gray-900">
                  They don't just automate tasks. They orchestrate entire workflows.
                </p>
              </div>
              
              {/* Workflow Examples */}
              <div className="bg-gray-50 rounded-2xl p-8 space-y-6">
                <div className="space-y-4">
                  <div className="flex items-start space-x-4">
                    <div className="w-2 h-2 bg-purple-400 rounded-full mt-3"></div>
                    <p className="text-lg font-light text-gray-700">
                      A lease expiry triggers renewal notices, rent reviews and calendar invites.
                    </p>
                  </div>
                  
                  <div className="flex items-start space-x-4">
                    <div className="w-2 h-2 bg-purple-400 rounded-full mt-3"></div>
                    <p className="text-lg font-light text-gray-700">
                      A tenant logs a maintenance request, and the Module troubleshoots the issue, dispatches the right tradesperson, follows up and closes the loop.
                    </p>
                  </div>
                  
                  <div className="flex items-start space-x-4">
                    <div className="w-2 h-2 bg-purple-400 rounded-full mt-3"></div>
                    <p className="text-lg font-light text-gray-700">
                      A new listing instantly generates a full marketing pack, compliant lease docs and a scheduled inspection run, all in minutes, not days.
                    </p>
                  </div>
                </div>
                
                <p className="text-lg font-medium text-gray-900 pt-4">
                  It's not about replacing people. It's about giving teams the leverage they've never had.
                </p>
              </div>
            </div>

            {/* Australian Focus */}
            <div className="space-y-8">
              <h2 className="text-3xl md:text-4xl font-light text-gray-900 leading-tight">
                Built for Australian property professionals
              </h2>
              
              <div className="space-y-6 text-lg leading-relaxed font-light text-gray-700">
                <p>
                  Abode is built for how property actually works in Australia. We've embedded legislative awareness into the core of the platform, from Form 18a tenancy agreements in Queensland to smoke alarm compliance, trust accounting rules and digital audit trails.
                </p>
                
                <p className="text-xl font-medium text-gray-900">
                  Your system won't just keep up with regulation. It will help you stay ahead of it.
                </p>
                
                <p>
                  Whether you manage 30 properties or 3,000, Abode gives you visibility, control and scale. From the smallest task to the largest campaign, everything connects. Every job, every conversation, every document is tracked, learnable and traceable.
                </p>
                
                <p className="text-xl font-medium text-gray-900">
                  No more spreadsheets. No more double-handling. No more compliance panic. Just clarity.
                </p>
              </div>
            </div>

            {/* Evolution */}
            <div className="space-y-8">
              <h2 className="text-3xl md:text-4xl font-light text-gray-900 leading-tight">
                This isn't software. It's a system that thinks
              </h2>
              
              <div className="space-y-6 text-lg leading-relaxed font-light text-gray-700">
                <p>
                  Because Abode is AI-generated, it evolves constantly. It learns from your team, your processes and your preferences. If your agency updates how it communicates with landlords or changes its inspection templates, you only have to update it once — the system takes care of the rest.
                </p>
                
                <p>
                  Every time you interact with Abode, it improves. Every module you train makes the platform stronger for your entire organisation. This is software that learns by doing. That improves while you work. That adapts without the pain of version control or feature rollouts.
                </p>
                
                <p className="text-xl font-medium text-gray-900">
                  We don't ship features quarterly. Abode rewrites itself daily.
                </p>
              </div>
            </div>

            {/* Future */}
            <div className="space-y-8 pb-16">
              <h2 className="text-3xl md:text-4xl font-light text-gray-900 leading-tight">
                The future of property management has arrived
              </h2>
              
              <div className="space-y-6 text-lg leading-relaxed font-light text-gray-700">
                <p>
                  The traditional property management platform is bloated, slow and outdated. Abode is the opposite. It's lean, fast, autonomous and built to help you focus on what actually matters: people, properties and performance.
                </p>
                
                <p>
                  If you're tired of tools that get in the way instead of getting work done, Abode is for you.
                </p>
                
                <p className="text-xl font-medium text-gray-900">
                  We're not here to tweak the old model. We're here to replace it.
                </p>
              </div>
              
              {/* Final Statement */}
              <div className="bg-gradient-to-r from-purple-50 to-orange-50 rounded-2xl p-8 mt-12">
                <div className="text-center space-y-4">
                  <h3 className="text-2xl font-light text-gray-900">
                    This is the next generation of property management
                  </h3>
                  <p className="text-lg font-light text-gray-700">
                    AI-generated. Fully autonomous. Built for the real world.
                  </p>
                  <p className="text-xl font-medium text-gray-900">
                    This is Abode.
                  </p>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>
    </div>
  )
}